package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"

	"github.com/panozzaj/fireup/internal/diff"
)

// cmdPorts handles the 'ports' command for managing DNS resolution
func cmdPorts(args []string) {
	if len(args) == 0 {
		printPortsUsage()
		os.Exit(0)
	}

	subcmd := args[0]
	subargs := args[1:]

	switch subcmd {
	case "install":
		cmdPortsInstall(subargs)
	case "uninstall":
		cmdPortsUninstall(subargs)
	case "-h", "--help", "help":
		printPortsUsage()
		os.Exit(0)
	default:
		fmt.Fprintf(os.Stderr, "Unknown ports command: %s\n\n", subcmd)
		printPortsUsage()
		os.Exit(1)
	}
}

func printPortsUsage() {
	fmt.Println(`fireup ports - Manage DNS resolution for .test domains

USAGE:
    fireup ports <command>

COMMANDS:
    install     Setup DNS resolver for .test domains
    uninstall   Remove DNS resolver configuration

Use 'fireup status' to check DNS status.

DESCRIPTION:
    Manages the macOS DNS resolver that routes *.test domains to
    fireup's built-in DNS server. fireup binds directly to ports
    80 and 443 — no port forwarding rules are needed.`)
}

// cmdPortsInstall handles the 'ports install' command
func cmdPortsInstall(args []string) {
	fs := flag.NewFlagSet("ports install", flag.ExitOnError)

	var (
		tld       string
		configDir string
	)

	fs.StringVar(&tld, "tld", "test", "Top-level domain to configure")
	fs.StringVar(&configDir, "dir", getDefaultConfigDir(), "Configuration directory")

	fs.Usage = func() {
		fmt.Println(`fireup ports install - Setup DNS resolution

USAGE:
    fireup ports install [options]

OPTIONS:`)
		fs.PrintDefaults()
		fmt.Println(`
DESCRIPTION:
    Creates a DNS resolver file so macOS routes *.test domains to
    fireup's built-in DNS server. fireup binds directly to ports
    80 and 443 — no port forwarding rules are needed.

    Requires sudo for writing to /etc/resolver/.

EXAMPLES:
    fireup ports install              # Setup for .test (default)
    fireup ports install --tld dev    # Setup for .dev TLD`)
	}

	// Check for help before parsing
	for _, arg := range args {
		if arg == "-h" || arg == "--help" || arg == "help" {
			fs.Usage()
			os.Exit(0)
		}
	}

	fs.Parse(args)

	requireNotAgent("ports install")
	if err := runPortsInstall(configDir, tld); err != nil {
		log.Fatalf("DNS setup failed: %v", err)
	}
}

// cmdPortsUninstall handles the 'ports uninstall' command
func cmdPortsUninstall(args []string) {
	fs := flag.NewFlagSet("ports uninstall", flag.ExitOnError)

	var tld string
	fs.StringVar(&tld, "tld", "test", "Top-level domain to remove")

	fs.Usage = func() {
		fmt.Println(`fireup ports uninstall - Remove DNS resolver config

USAGE:
    fireup ports uninstall [options]

OPTIONS:`)
		fs.PrintDefaults()
		fmt.Println(`
DESCRIPTION:
    Removes the DNS resolver file for the specified TLD.

    Requires sudo for modifying /etc/resolver/.

EXAMPLES:
    fireup ports uninstall              # Remove .test config (default)
    fireup ports uninstall --tld dev    # Remove .dev TLD config`)
	}

	// Check for help before parsing
	for _, arg := range args {
		if arg == "-h" || arg == "--help" || arg == "help" {
			fs.Usage()
			os.Exit(0)
		}
	}

	fs.Parse(args)

	requireNotAgent("ports uninstall")
	if err := runPortsUninstall(tld); err != nil {
		log.Fatalf("DNS removal failed: %v", err)
	}
}

// getResolverContent returns the DNS resolver file content
func getResolverContent() string {
	return fmt.Sprintf("# Generated by fireup\nnameserver 127.0.0.1\nport %d\n", DefaultDNSPort)
}

// portsInstallPlan returns a Plan for DNS resolver installation.
func portsInstallPlan(tld string) *diff.Plan {
	plan := diff.NewPlan()

	if tld != "localhost" {
		resolverPath := fmt.Sprintf("/etc/resolver/%s", tld)
		plan.CreateStatic(resolverPath, getResolverContent())
	}

	return plan
}

// portsUninstallPlan returns a Plan for DNS resolver removal.
func portsUninstallPlan(tld string) *diff.Plan {
	plan := diff.NewPlan()

	if tld != "localhost" {
		plan.Delete(fmt.Sprintf("/etc/resolver/%s", tld))
	}

	return plan
}

// confirmPortsInstall shows a summary and confirms DNS resolver installation.
func confirmPortsInstall(tld, prompt string) bool {
	if os.Getenv("FIREUP_YES") == "1" {
		return true
	}
	if isAgent() {
		fmt.Fprintf(os.Stderr, "Error: interactive prompt not supported in agent mode.\nUse FIREUP_YES=1 to skip confirmations.\n")
		return false
	}

	plan := portsInstallPlan(tld)
	summary := plan.Summary()

	if summary == nil {
		return true
	}

	fmt.Println()
	summary.Print()

	for {
		fmt.Printf("%s [y/N, ? for diff]: ", prompt)
		var response string
		fmt.Scanln(&response)

		switch response {
		case "y", "Y":
			return true
		case "?":
			fmt.Println()
			plan.Preview()
		default:
			return false
		}
	}
}

func runPortsInstall(configDir, tld string) error {
	// If not running as root, check for conflicts and re-invoke with sudo
	if os.Geteuid() != 0 {
		if err := checkInstallConflicts(tld); err != nil {
			return err
		}

		fmt.Println("DNS resolver setup requires administrator privileges.")
		if !confirmPortsInstall(tld, "Proceed with installation?") {
			return fmt.Errorf("installation cancelled")
		}
		fmt.Println()

		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("finding executable: %w", err)
		}

		args := []string{exe, "ports", "install", "--tld", tld, "--dir", configDir}
		cmd := exec.Command("sudo", args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Stdin = os.Stdin
		return cmd.Run()
	}

	// Running as root
	fmt.Println("Installing DNS resolver...")

	// Save TLD to config
	if err := saveGlobalConfig(configDir, &GlobalConfig{TLD: tld}); err != nil {
		fmt.Printf("Warning: could not save config: %v\n", err)
	}

	if tld != "localhost" {
		if err := os.MkdirAll("/etc/resolver", 0755); err != nil {
			return fmt.Errorf("creating resolver directory: %w", err)
		}
	}

	plan := portsInstallPlan(tld)
	if err := plan.Execute(); err != nil {
		return err
	}

	fmt.Println()
	fmt.Println("DNS resolver installed!")
	fmt.Printf("  - TLD: .%s\n", tld)
	fmt.Printf("  - Resolver: /etc/resolver/%s\n", tld)

	return nil
}

func runPortsUninstall(tld string) error {
	if !isDNSInstalled(tld) {
		fmt.Printf("%s✓ DNS resolver is not installed%s\n", colorGreen, colorReset)
		fmt.Printf("  Not found: /etc/resolver/%s\n", tld)
		return nil
	}

	if os.Geteuid() != 0 {
		plan := portsUninstallPlan(tld)
		fmt.Println("Removing DNS resolver requires administrator privileges.")
		if !confirmWithPlan(plan, "Proceed with removal?") {
			return fmt.Errorf("removal cancelled")
		}
		fmt.Println()

		exe, err := os.Executable()
		if err != nil {
			return fmt.Errorf("finding executable: %w", err)
		}

		args := []string{exe, "ports", "uninstall", "--tld", tld}
		cmd := exec.Command("sudo", args...)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		cmd.Stdin = os.Stdin
		return cmd.Run()
	}

	fmt.Println("Removing DNS resolver...")

	plan := portsUninstallPlan(tld)
	if err := plan.Execute(); err != nil {
		return err
	}

	fmt.Printf("%s✓ DNS resolver removed%s\n", colorGreen, colorReset)

	return nil
}
